# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2000-2021
  project: LDAP / SSO Authentication
  version: 3.7-dev
  release: 3.7.0-dev
  latex_documents:
  - - Index
    - ig_ldap_sso_auth.tex
    - LDAP / SSO Authentication
    - Xavier Perseguers
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  latex_show_pagerefs: True
  extensions:
    - sphinx.ext.intersphinx
    - t3sphinx.ext.t3extras
    - t3sphinx.ext.t3tablerows
    - t3sphinx.ext.targets
    - sphinx.ext.extlinks
  extlinks:
    ter:
    - https://extensions.typo3.org/extension/%s/
    - 'EXT:'
  intersphinx_mapping:
    t3api:
    - https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/
    - null
    t3tsref:
    - https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/
    - null
...
